// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldName     string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldValue    string                 `protobuf:"bytes,2,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageField) Reset() {
	*x = MessageField{}
	mi := &file_dog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageField) ProtoMessage() {}

func (x *MessageField) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageField.ProtoReflect.Descriptor instead.
func (*MessageField) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{0}
}

func (x *MessageField) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *MessageField) GetFieldValue() string {
	if x != nil {
		return x.FieldValue
	}
	return ""
}

type NotificationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromService   string                 `protobuf:"bytes,1,opt,name=from_service,json=fromService,proto3" json:"from_service,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Header        string                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Fields        []*MessageField        `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMessage) Reset() {
	*x = NotificationMessage{}
	mi := &file_dog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMessage) ProtoMessage() {}

func (x *NotificationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMessage.ProtoReflect.Descriptor instead.
func (*NotificationMessage) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationMessage) GetFromService() string {
	if x != nil {
		return x.FromService
	}
	return ""
}

func (x *NotificationMessage) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *NotificationMessage) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *NotificationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *NotificationMessage) GetFields() []*MessageField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorText     string                 `protobuf:"bytes,2,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_dog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_dog_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NotificationResponse) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

var File_dog_proto protoreflect.FileDescriptor

const file_dog_proto_rawDesc = "" +
	"\n" +
	"\tdog.proto\x12\x03dog\"N\n" +
	"\fMessageField\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x1f\n" +
	"\vfield_value\x18\x02 \x01(\tR\n" +
	"fieldValue\"\xcf\x01\n" +
	"\x13NotificationMessage\x12!\n" +
	"\ffrom_service\x18\x01 \x01(\tR\vfromService\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06header\x18\x03 \x01(\tR\x06header\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12)\n" +
	"\x06fields\x18\x06 \x03(\v2\x11.dog.MessageFieldR\x06fields\"I\n" +
	"\x14NotificationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"error_text\x18\x02 \x01(\tR\terrorText2Q\n" +
	"\n" +
	"DogService\x12C\n" +
	"\fNotification\x12\x18.dog.NotificationMessage\x1a\x19.dog.NotificationResponseB*Z(github.com/savageking-io/savagedog/protob\x06proto3"

var (
	file_dog_proto_rawDescOnce sync.Once
	file_dog_proto_rawDescData []byte
)

func file_dog_proto_rawDescGZIP() []byte {
	file_dog_proto_rawDescOnce.Do(func() {
		file_dog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dog_proto_rawDesc), len(file_dog_proto_rawDesc)))
	})
	return file_dog_proto_rawDescData
}

var file_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dog_proto_goTypes = []any{
	(*MessageField)(nil),         // 0: dog.MessageField
	(*NotificationMessage)(nil),  // 1: dog.NotificationMessage
	(*NotificationResponse)(nil), // 2: dog.NotificationResponse
}
var file_dog_proto_depIdxs = []int32{
	0, // 0: dog.NotificationMessage.fields:type_name -> dog.MessageField
	1, // 1: dog.DogService.Notification:input_type -> dog.NotificationMessage
	2, // 2: dog.DogService.Notification:output_type -> dog.NotificationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dog_proto_init() }
func file_dog_proto_init() {
	if File_dog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dog_proto_rawDesc), len(file_dog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dog_proto_goTypes,
		DependencyIndexes: file_dog_proto_depIdxs,
		MessageInfos:      file_dog_proto_msgTypes,
	}.Build()
	File_dog_proto = out.File
	file_dog_proto_goTypes = nil
	file_dog_proto_depIdxs = nil
}
